controller_type: 1

takeoff_state:
    height: 4.0 # m

fsmparam:
    frequncy: 100

kine_cons:
    vel_ver_max: 1.0
    vel_hor_max: 1.0
    acc_ver_max: 0.2
    acc_hor_max: 0.2

gain: 
    Kvp0: 1.0 #2.0
    Kvp1: 1.0 #1.5
    Kvp2: 1.0 #1.5
    Kvi0: 1.5 #1.8
    Kvi1: 1.5 #1.8
    Kvi2: 1.5 #1.8
    Kvd0: 1.0
    Kvd1: 1.0
    Kvd2: 1.0

msg_timeout:
    odom: 0.5
    rc:   0.5
    cmd:  0.1
    imu:  0.5
    bat:  0.5
