planner_fre: 150

max_vel_hor: 1.5

max_vel_ver: 1.5

max_omega: 0.26

target_pos_inflation: 0.15

target_yaw_inflation: 0.1

route_list_x: [0.0, 10.0]

route_list_y: [0.0, 0.0]

route_list_z: [1.5, 1.5]

route_list_yaw: [0.0, 0.5]