planner_fre: 150

max_vel_hor: 1.5

max_vel_ver: 1.5

max_omega: 0.26

target_pos_inflation: 0.1

target_yaw_inflation: 0.1

route_list_x: [0.0, 5.0, 7.0, 15.0, 30.0]

route_list_y: [0.0, 0.0, 5.0, 6.0, 0.0]

route_list_z: [4.0, 4.0, 4.0, 4.0, 4.0]

route_list_yaw: [0.0, 0.26, 0.50, -1.0, 0.0]